config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  validates :title,      presence: true, length: { maximum: 50 }
  validates :start_date, presence: true
  validates :end_date,   presence: true
  validate :start_end_check

  # 開始日より終了日の方が前だった場合にfalseを返す

  def start_end_check
    if self.start_date && self.end_date
      errors.add(:end_date, "は開始日より前の日付には登録できません。") unless self.start_date <= self.end_date 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_tasks
  helper_method :sort_column, :sort_direction

  def index
    @tasks = Task.all.order("#{sort_column} #{sort_direction}")
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:info] = "新規スケジュールが作成されました"
      redirect_to tasks_path
    else
      render "new"
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success] = "スケジュールが更新されました"
      redirect_to tasks_path
    else
      render "edit"
    end
  end

  def destroy
    Task.find(params[:id]).destroy
    flash[:success] = "スケジュールを削除しました"
    redirect_to tasks_path
  end

  private
    def task_params
      params.require(:task).permit(:title, :start_date, :end_date, :all_day, :memo)
    end

    def get_tasks
      @tasks = Task.all
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
      
    def sort_column
      Task.column_names.include?(params[:sort]) ? params[:sort] : 'id'
    end
      

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper

  def sort_order(column, title)
    direction = (column == sort_column && sort_direction == 'asc') ? 'desc' : 'asc'
    # link_to title, { sort: column, direction: direction }
    link_to title, tasks_path( sort: column, direction: direction )
  end
  
  end

app/views/layouts/_footer.html.erb
<footer>
  <h1>現在の日時 : <%= Date.current.strftime("%Y年 %m月 %d日") %>
      　スケジュール合計 : <%= @tasks.count%>
  </h1>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1>Ruby on Rails スケジュール管理アプリ</h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= object.errors.count %>個の入力エラーがあります！
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="main_container">
    <div class="information">
    <h2>スケジュール編集</h2>
</div>
    
<%= form_with(model: @task, local: true) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <table>
    <tbody>
      <tr>
        <th><%= f.label "タイトル" %></th>
        <td><%= f.text_field :title, class: "form-control" %></td>
      </tr>
      <tr>
          <th><<%= f.label "開始日" %></th>
          <td><%= f.date_field :start_date, class: "form-control" %></td>
      </tr>
      <tr>
          <th><%= f.label "終了日" %>></th>
          <td><%= f.date_field :end_date, class: "form-control" %></td>
      </tr>
      <tr>
          <th><%= f.label "終日？" %></th>
          <td><%= f.check_box :all_day %><span>終日の場合はチェックを入れてね！</span></td>
      </tr>
      <tr>
          <th><%= f.label "スケジュールメモ" %></th>
          <td><%= f.text_area :memo, class: "form-control" %></td>
      </tr>
    </tbody>
  </table>
  <div class="submit">
    <ul>
      <li><%= f.submit "スケジュールの編集を完了する", class: "btn btn-primary" %></li>
      <li><%= link_to "スケジュール一覧に戻る", tasks_path %>
    </ul>
  </div>
<% end %>

app/views/tasks/index.html.erb
<div class="main_container">
  <div class="information">
    <h2>スケジュール一覧</h2>
  </div>
  <table>
    <thead>
      <tr>
        <th><%= sort_order "id", "ID" %></th>
        <th><%= sort_order "title", "タイトル" %></th>
        <th><%= sort_order "start_date", "開始日" %></th>
        <th><%= sort_order "end_date", "終了日" %></th>
        <th><%= sort_order "all_day", "終日" %></th>
        <th><%= sort_order "updated_at", "スケジュール更新日時" %></th>
        <th>確認</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.id %></td>
          <td><%= link_to "#{task.title}", task %></td>
          <td><%= task.start_date.strftime("%Y年%m月%d日") %></td>
          <td><%= task.end_date.strftime("%Y年%m月%d日") %></td>
          <% if task.all_day == true %>
            <td><strong>○</strong></td>
          <% else %>
          <td>   </td>
          <% end %>
          <td><%= task.updated_at.strftime("%Y年%m月%d日 %H時%M分") %></td>
          <td><%= link_to "確認", task %></td>
          <td><%= link_to "編集", edit_task_path(task) %></td>
          <td><%= link_to "削除", task_path(task), method: :delete, data: { confirm: "本当に削除しますか" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p><%= link_to "スケジュール新規登録", new_task_path%></p>
</div>

app/views/tasks/new.html.erb
<div class="main_container">
  <div class="information">
  <h2>スケジュール新規作成</h2>
</div>

<%= form_with(model: @task, local: true) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <table>
    <tbody>
      <tr>
        <th><%= f.label "※タイトル" %></th>
        <td><%= f.text_field :title, class: "form-control" %></td>
      </tr>
      <tr>
          <th><%= f.label "※開始日" %></th>
          <td><%= f.date_field :start_date, class: "form-control" %></td>
      </tr>
      <tr>
          <th><%= f.label "※終了日" %></th>
          <td><%= f.date_field :end_date, class: "form-control" %></td>
      </tr>
      <tr>
          <th><%= f.label "終日" %></th>
          <td><%= f.check_box :all_day %><span>終日の場合はチェックを入れてね！</span></td>
      </tr>
      <tr>
          <th><%= f.label "スケジュールメモ" %></th>
          <td><%= f.text_area :memo, class: "form-control" %></td>
      </tr>
    </tbody>
  </table>
  <p>※は必須項目です</p>

  <div class="submit">
    <ul>
      <li class="submit-li"><%= f.submit "スケジュールを新規登録する" %></li>
      <li><%= link_to "スケジュール一覧に戻る", tasks_path %>
    </ul>
  </div>
<% end %>

app/views/tasks/show.html.erb
<div class="main_container">
  <div class="information">
    <h2>スケジュール詳細</h2>
  </div>
  <table> 
    <tbody>
      <tr>
        <th>タイトル</th>
        <td><%= @task.title %></td>
      </tr>
      <tr>
        <th>開始日</th>
        <td><%= @task.start_date %></td>
      </tr>
      <tr>
        <th>投稿日時</th>
        <td><%= @task.end_date %></td>
      </tr>
      <tr>
          <th>終日</th>
          <% if @task.all_day == true %>
            <td><strong>○</strong></td>
          <% else %>
            <td>   </td>
          <% end %>
      </tr>
      <tr>
          <th>スケジュールメモ</th>
          <td><%= @task.memo %></td>
      </tr>
    </tbody>
  </table>

  <ul>
    <li><%= link_to "スケジュール一覧に戻る", tasks_path %></li>
    <li><%= link_to "スケジュールを編集する", edit_task_path(@task) %></li>
    <li>
      <%= link_to "スケジュールを削除", tasks_path(@task), method: :delete, date: { confirm: "本当に削除しますか？" } %>
    </li>
  </ul>
</div>